version: '3.7'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - observability

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - /loki:/loki
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"       # porta HTTP para Tempo API (query, status)
      - "44317:44317"       # OTLP gRPC
      - "4318:4318"       # OTLP HTTP (se quiser adicionar também)
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - /tmp/tempo:/tmp/tempo
    command: ["-config.file=/etc/tempo.yaml"]
    networks:
      - observability

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009"
    networks:
      - observability
    environment:
      - MINIO_BUCKET=mybucket

networks:
  observability:
    driver: bridge

volumes:
  grafana-data:

