auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  wal:
    dir: /loki/wal

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    resync_interval: 1m
  aws:
    s3: "s3://your-bucket-name"
    access_key_id: "your-access-key-id"
    secret_access_key: "your-secret-access-key"
    region: "us-east-1"

chunk_store_config:
  max_look_back_period: 0s

